version: '3.9'

services:
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password --innodb-flush-log-at-trx-commit=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-networking=0 --max_allowed_packet=500M
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: influencer_database
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql